apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bjox
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0003-tenant/cin4s-839-0003-app/devfile-sample-bjox@sha256:adb292a9dbb8b6da19453ac9eed0d7b35f644382eea378328327470c770741be
        name: my-nodejs
        resources: {}
status: {}
